name: hillel auto e2e tests

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, reopened]


env: 
    SITEAUTHUSERNAME: ${{ secrets.SITEAUTHUSERNAME }}
    SITEAUTHPASSWORD: ${{ secrets.SITEAUTHPASSWORD }}
  
jobs:
  playwright_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install playwright

    - name: Install browsers
      run: npx playwright install

    - name: Install WebKit dependencies 
      run: sudo apt-get install -y libx264-dev libhyphen0 libvpx7 libevent-2.1-7 libopus0 libharfbuzz-icu0 libgstallocators-1.0-0 libgstapp-1.0-0 libgstpbutils-1.0-0 libgstaudio-1.0-0 libgsttag-1.0-0 libgstvideo-1.0-0 libgstgl-1.0-0 libgstcodecparsers-1.0-0 libgstfft-1.0-0 libmanette-0.2-0 libflite1 libflite-usenglish1 libflite-cmu-grapheme-lang1 libflite-cmu-grapheme-lex1 libflite-cmu-indic-lang1 libflite-cmu-indic-lex1 libflite-cmulex1 libflite-cmu-time-awb1 libflite-cmu-us-awb1 libflite-cmu-us-kal16-1 libflite-cmu-us-kal1 libflite-cmu-us-rms1 libflite-cmu-us-slt1 libgles2 libx264-155
    

    - name: Run Playwright Tests
      run: npx playwright test 

 

   
